sudo: false
language: cpp
dist: xenial
addons:
  apt:
    packages:
      - libmpich-dev
before_install:
  - pushd ${HOME}
  - wget http://releases.llvm.org/7.0.1/clang+llvm-7.0.1-x86_64-linux-gnu-ubuntu-16.04.tar.xz
  - wget https://github.com/Kitware/CMake/releases/download/v3.15.5/cmake-3.15.5-Linux-x86_64.tar.gz
  - wget -O adios_master.zip https://github.com/ornladios/ADIOS2/archive/master.zip
  - popd
install:
  - sudo apt-get install libblosc1 libblosc-dev
  - git reset --hard ${TRAVIS_PULL_REQUEST_SHA}
  - mkdir build && pushd build && cmake .. && make && sudo make install && popd
  - pushd ${HOME}
  - tar -xf clang+llvm-7.0.1-x86_64-linux-gnu-ubuntu-16.04.tar.xz
  - export PATH="${PWD}/clang+llvm-7.0.1-x86_64-linux-gnu-ubuntu-16.04/bin:${PATH}"
  - tar -zxf cmake-3.15.5-Linux-x86_64.tar.gz
  - export PATH="${PWD}/cmake-3.15.5-Linux-x86_64/bin:${PATH}"
  - unzip adios_master.zip
  - pushd ADIOS2-master && mkdir build && pushd build && cmake -DADIOS2_USE_MPI=ON ..  && make && sudo make install && popd && popd
  - export PATH="${PWD}/ADIOS2-2.5.0/bin:${PATH}"
  - popd
  - echo ${PWD}
  - mkdir build1 && pushd build1 && echo ${PWD} && cmake .. & make && sudo make install && popd
  - pip install --user flake8
  - git config --global clangformat.binary ${HOME}/clang+llvm-7.0.1-x86_64-linux-gnu-ubuntu-16.04/bin/clang-format
  - ./scripts/travis/build-cppcheck.sh
env:
  matrix:
    - BUILD_MATRIX_ENTRY=format
    - BUILD_MATRIX_ENTRY=analyze
    - BUILD_MATRIX_ENTRY=check
    - BUILD_MATRIX_ENTRY=test-gs  
script:
  - git reset --hard ${TRAVIS_PULL_REQUEST_SHA}
  - ${TRAVIS_BUILD_DIR}/scripts/travis/run.sh
